apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: 'gcr.io/opsmx-project/webappimg:latest'
          name: webapp-pod
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: webapp
  type: ClusterIP
